name: Meu site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Definir nome da imagem
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/site:latest" >> $GITHUB_ENV

      - name: Construir e fazer push da imagem Docker
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Criar diretório para manifestos na pasta específica
        run: mkdir -p k8s/deployments

      - name: Gerar arquivo deployment.yaml
        run: |
          cat <<EOF > k8s/deployments/deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mysite
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mysite
            template:
              metadata:
                labels:
                  app: mysite
              spec:
                containers:
                  - name: mysite
                    image: sauloshs/site:latest
                    ports:
                      - containerPort: 8080
          EOF

      - name: Commit e Push do arquivo manifesto na pasta específica
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployments/deployment.yaml
          git commit -m "Atualizando deployment.yaml na pasta k8s/deployments"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
